//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnPictureViewer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KnPictureViewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;rss version=&quot;2.0&quot;&gt;
        ///  &lt;channel&gt;
        ///    &lt;title&gt;Kn Video Studio LLC www.knvideostudio.com&lt;/title&gt;
        ///    &lt;link&gt;http://www.knvideostudio.com&lt;/link&gt;
        ///    &lt;description&gt;Kn Video Studio LLC. www.knvideostudio.com&lt;/description&gt;
        ///    &lt;language&gt;en-us&lt;/language&gt;
        ///    &lt;ttl&gt;1440&lt;/ttl&gt;
        ///    &lt;item&gt;
        ///      &lt;title&gt;Small Boat is loast in the sea.&lt;/title&gt;
        ///      &lt;description&gt;The boat is swiming to find the right direction to the island ...&lt;/description&gt;
        ///      &lt;link&gt;http://www.knvideostudio.com&lt;/link&gt;
        ///    &lt;/item&gt;
        ///    &lt;item&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefaultRSSText {
            get {
                return ResourceManager.GetString("DefaultRSSText", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap knboat1 {
            get {
                object obj = ResourceManager.GetObject("knboat1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap knboat2 {
            get {
                object obj = ResourceManager.GetObject("knboat2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap knboot {
            get {
                object obj = ResourceManager.GetObject("knboot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap knCubes {
            get {
                object obj = ResourceManager.GetObject("knCubes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap knflower1 {
            get {
                object obj = ResourceManager.GetObject("knflower1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap knflower2 {
            get {
                object obj = ResourceManager.GetObject("knflower2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap knfruit {
            get {
                object obj = ResourceManager.GetObject("knfruit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kngreen {
            get {
                object obj = ResourceManager.GetObject("kngreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap knhouse1 {
            get {
                object obj = ResourceManager.GetObject("knhouse1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap knhouse2 {
            get {
                object obj = ResourceManager.GetObject("knhouse2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap knhouse3 {
            get {
                object obj = ResourceManager.GetObject("knhouse3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap knpeaches {
            get {
                object obj = ResourceManager.GetObject("knpeaches", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap knplien {
            get {
                object obj = ResourceManager.GetObject("knplien", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap knpot {
            get {
                object obj = ResourceManager.GetObject("knpot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap knroster1 {
            get {
                object obj = ResourceManager.GetObject("knroster1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap knroster2 {
            get {
                object obj = ResourceManager.GetObject("knroster2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap knroster3 {
            get {
                object obj = ResourceManager.GetObject("knroster3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap knsun {
            get {
                object obj = ResourceManager.GetObject("knsun", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kntractor {
            get {
                object obj = ResourceManager.GetObject("kntractor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kntree {
            get {
                object obj = ResourceManager.GetObject("kntree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
